import express from 'express';
import {ApiHealthCheckRouter} from './controllers/api-health-check';
import {AuthRouter} from './controllers/auth';
import {OrganizationTypeRouter} from './controllers/organization-type';
import {UserRouter} from './controllers/user';
import {CompanyTypeRouter} from './controllers/company-type/company-type.router';
import {OrganizationNameRouter} from './controllers/organization-name/organization-name.router';
import {SendEmailRouter} from './controllers/send-email/send-email.router';
import {CountryRouter} from './controllers/country';
import {CityRouter} from './controllers/city/city.router';
import {PublicCompRouter} from './controllers/public-company/public-company.router';
import {PriorityLevelRouter} from './controllers/priority-level/priority-level.router';
import {StakeHolderLinksRouter} from './controllers/stakeholder-links/stakeholder-links.router';
import {StakeholderRouter} from './controllers/stakeholder/stakeholder.router';
import {MeetingsRouter} from './controllers/meetings';
import {FaqRouter} from './controllers/faqs';
import {ManagerDashboardRouter} from './controllers/manager-dashboard/manager-dashboard.router';
import {UserNotificationRouter} from './controllers/userNotificaiton';
import {AdminDashboardRouter} from './controllers/admin-dashboard';
import {EntityRouter} from './controllers/entity';
import {DesignationRouter} from './controllers/designation';
import {AttendeeRouter} from './controllers/attendee';
import {FaqTypesRouter} from './controllers/faq-types';
import {RolesRouter} from './controllers/roles';
export const AppRouter = express.Router();

AppRouter.use('/api-health-check', ApiHealthCheckRouter);
AppRouter.use('/user', UserRouter);
AppRouter.use('/auth', AuthRouter);
AppRouter.use('/api-admin', AuthRouter);
AppRouter.use('/organization', OrganizationTypeRouter);
AppRouter.use('/organization', OrganizationNameRouter);
AppRouter.use('/company', CompanyTypeRouter);
AppRouter.use('/company', PublicCompRouter);
AppRouter.use('/country', CountryRouter);
AppRouter.use('/prioritylevel', PriorityLevelRouter);
AppRouter.use('/stakeholder', StakeHolderLinksRouter);
AppRouter.use('/stakeholder', StakeholderRouter);
AppRouter.use('/city', CityRouter);
AppRouter.use('/send-email', SendEmailRouter);
AppRouter.use('/meetings', MeetingsRouter);
AppRouter.use('/faq', FaqRouter);
AppRouter.use('/dashboard', ManagerDashboardRouter);
AppRouter.use('/notification', UserNotificationRouter);
AppRouter.use('/admin-dashboard', AdminDashboardRouter);
AppRouter.use('/entity', EntityRouter);
AppRouter.use('/designation', DesignationRouter);
AppRouter.use('/attendee', AttendeeRouter);
AppRouter.use('/faqTypes', FaqTypesRouter);
AppRouter.use('/roles', RolesRouter);
